"""changed allergies to name

Revision ID: 8bfc147d9672
Revises: 19d2a8e6420d
Create Date: 2021-07-01 17:24:08.783696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bfc147d9672'
down_revision = '19d2a8e6420d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allergies', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('allergies', 'allergies')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allergies', sa.Column('allergies', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('allergies', 'name')
    # ### end Alembic commands ###
